version: 2

jobs:
  test_esm:
    docker: [{ image: "circleci/node:12" }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - ESM
          command: yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test_cjs:
    docker: [{ image: "circleci/node:12" }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - CJS
          command: yarn run test:cjs:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test_umd:
    docker: [{ image: "circleci/node:12" }]
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - CJS
          command: yarn run test:umd:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  bundlesize:
    docker: [{ image: "circleci/node:12" }]
    steps:
      - checkout
      - run: yarn
      - run: yarn run bundlesize

  lint:
    docker: [{ image: "circleci/node:12" }]
    steps:
      - checkout
      - run: yarn
      - run: yarn format --check
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
      - test_esm
      - test_cjs
      - test_umd
      - bundlesize
