version: 2

jobs:
  test:
    docker: [{ image: "circleci/node:12" }]
    resource_class: large
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - ES
          command: yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/es-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test_cjs:
    docker: [{ image: "circleci/node:12" }]
    resource_class: large
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - CJS
          command: yarn run test:cjs:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/cjs-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test_umd:
    docker: [{ image: "circleci/node:12" }]
    resource_class: large
    steps:
      - checkout
      - run: yarn
      - run:
          name: Tests - UMD
          command: yarn run test:umd:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/umd-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  bundlesize:
    docker: [{ image: "circleci/node:12" }]
    resource_class: large
    steps:
      - checkout
      - run: yarn
      - run: yarn run bundlesize:ci

  lint:
    docker: [{ image: "circleci/node:12" }]
    resource_class: large
    steps:
      - checkout
      - run: yarn
      - run: yarn format --check
      - run: yarn lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
      - test
      - test_cjs
      - test_umd
